// (C) Anton Golubenko, Aditya Khadkikar, Akuien Deng - Group: 27 
// Work package 1 
// Exercise 3 
// Submission code: XXXXXXX (provided by your TA-s) 

/* 
    Including header files for functions of standard input and output, 
    as well as random num. generation through the standard libary and 
    string library for comparisons.
*/

#include <stdio.h>
#include <stdlib.h> 
#include <string.h>
#include <time.h>

// main function that returns an integer and takes in void as an argument
int main(void) {
    /* 
    * Declaring an integer "num" that stores a randomly generated number, mod 100 to fix it to be under 100, 
    * and +1 to ensure it is at least one when the modulo might be 0 in case of a perfect division.  
    */
    char response;

    // here the randomizer is set in a way that a random number is generated after each new execution
    srand(time(0));

    //using the settings in srand(), the rand() will return a new random number, which is manipulated later to fit between 1-100
    int* num = (int*) malloc(sizeof(int));
    *num = rand() % 100 + 1;

    //as the do-while loop is run at least once, the guess_count (number of guesses user has made so far), is initialised as 1.                                 
    int guess_count = 1;

    //variable for what the user guesses
    char guess[3];

    //max number of guesses a user is allowed to make
    const int MAX_NUMBER = 25;
    int guessed_num;

    // do whats in this block first before reaching the while condition.
    do {
        //prompts the user to enter a guess
        printf("\nGuess the number (between 1-100):  ");
        
        // take in the number from keyboard and store it in num variable
        scanf("%s", guess);
        guessed_num = atoi(guess); //the number that is scanned from the console is parsed to int for type-checking purposes

        if (guessed_num == 0 || strcmp(guess, "\n") == 0) {
            printf("\nPlease enter a valid guessable number.\n");
            //still adds as a valid guess when an incorrect format is provided
            guess_count++;
        } else if (guessed_num == *num) {
            //upon a successful guess of the number
            printf("\nYou have guessed %d times, and your guess is correct. \n\nWould you like to play again? \nType Y to continue, or anything else to quit. -- ", guess_count);
            //scans for another response, for if the user wants to continue with another round, or quit (anything except capital Y leads to quit)
            scanf("%s", &response);
            if (response == 'Y') {
                guess_count = 1;
                *num = rand() % 100 + 1;
            } else {
                printf("\nThanks for playing!\n");
                break;
            }
        } else if (guess_count == MAX_NUMBER) {
            printf("\nYou have guessed too many times. The number was %d. \n", *num); 
            //here the number of guesses are reset, and it breaks out of the while loop, terminating the program.
            guess_count = 0;
            break;
        } else if (guessed_num > 100 | guessed_num < 1) {
            //informs user to enter between 1-100 as per the requirements of the game
            printf("\nPlease enter a valid guessable number, kindly between 1 and 100.\n");
            guess_count++;
        } else if (guessed_num > *num) {
            //the case when the guess is higher than what the number is
            printf("\nYour guess is higher than the actual number. Keep guessing!\n");
            guess_count++;
        } else if (guessed_num < *num) {
            //the case when the guess is lower than what the number is
            printf("\nYour guess is lower than what the number is. Keep guessing....\n");
            guess_count++;
        } else {
            break;
        }
    } while (guess_count <= MAX_NUMBER);
    /* 
        the loop will keep running until either:
        - the guessed number is the same as the number generated by the computer
        or 
        - the user has guessed more than MAX_NUMBER times  
    */

    return 0; // return success
}
